global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['processor:8000']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']